name: CI

on:
  push:
    branches:
      - '**'  # Matches every branch
  pull_request:
    branches:
      - master

jobs:
  install-lint-and-test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: npnpm i

      - name: Typecheck
        run: npm run test:types

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
